# Generated by Django 4.2.5 on 2023-09-20 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('price', models.PositiveIntegerField()),
                ('isEloctrocar', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
